name: go_final_project
on:
   push:
     tags:
       - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.23.3
    - name: Build
      run: go build -v ./...
  test:
    needs: build
    runs-on: ubuntu-latest
    container: golang:1.23.3
    steps:
      - uses: actions/checkout@v4
      - name: Vet Tests
        run: |
          go vet ./...
      - name: Run Unit Tests
        run: |
          go run main.go&
          go test ./tests/...
          pkill main
  delivery:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: mozhnov/go_final_project

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Run on runner
    runs-on: runner1
    environment: staging
    if: startsWith(github.ref, 'refs/tags')
    needs: delivery
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: stop and remove befor conteiner
        run: |
          docker stop deploy
          docker rm deploy
      - name: Docker Pull Image
        run: docker pull mozhnov/go_final_project:latest
      - name: Run Image
        run: docker run -d -p 7540:7540 --name deploy mozhnov/go_final_project:latest